services:
  - type: web
    name: spring-backend
    env: docker
    plan: starter
    region: frankfurt
    autoDeployTrigger: checksPass

    buildCommand: ""
    startCommand: ""

    # sync: false means the Render dashboard will prompt us for the value on first deploy.
    # 'prod,seed' (comma-separated, no space).
    # Once seeded, change to 'prod' in the Dashboard and that will stop seeding logic.
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        sync: false

      # The URL is provided for the properties file which will prepend jdbc:
      - key: DB_HOST
        fromDatabase:
          name: backend-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: backend-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: backend-db
          property: database

      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: backend-db
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: backend-db
          property: password

      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate

      - key: JWT_SIGNING_KEY_BASE64
        sync: false

      - key: CLOUDFRONT_BASE_URL
        sync: false

    runtime: docker

databases:
  - name: backend-db
    plan: free
    region: frankfurt
